spring:
  profiles: default
my:
   servers:
       - dev.example.com
       - another.example.com

server:
    address: 192.168.1.100
---
spring:
    profiles: development
server:
    address: 127.0.0.1

acme:
    remote-address: 192.168.1.1
    security:
        username: admin
        roles:
          - USER
          - ADMIN
    list:
        - name: my name
          description: my description
    map:
        key1:
          name: dev name 1
        key2:
          name: dev name 2
          description: dev description 2

---
spring:
    profiles: production & eu-central
server:
    address: 192.168.1.120